# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
version: '3.3'
volumes:
  metricbeat:
services:
  mongo1:
    image: mongo:4.4
    restart: unless-stopped

  redis:
    image: redis:5
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node

  influxdb:
    image: influxdb:1.7.9
    restart: unless-stopped

  hearth:
    image: jembi/hearth:v1.0.0-beta.3
    environment:
      - mongodb__url=mongodb://mongo1/hearth-dev
      - logger__level=warn
      - authentication__type=disabled
      - idGenerator=uuidv4
      - server__fhirVersion=stu3
    depends_on:
      - mongo1
    restart: unless-stopped

  openhim-core:
    image: jembi/openhim-core:7
    environment:
      - mongo_url=mongodb://mongo1/openhim-dev
      - mongo_atnaUrl=mongodb://mongo1/openhim-dev
      - logger_level=error
    depends_on:
      - mongo1
    restart: unless-stopped

  openhim-console:
    image: jembi/openhim-console:1.13
    restart: unless-stopped
