# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
version: '3.3'

services:
  client:
    image: opencrvs/ocrvs-client:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    restart: unless-stopped

  components:
    image: opencrvs/ocrvs-components:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/components/Dockerfile
    restart: unless-stopped
  login:
    image: opencrvs/ocrvs-login:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/login/Dockerfile
    restart: unless-stopped
  gateway:
    image: opencrvs/ocrvs-gateway:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/gateway/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - CONFIG_SMS_CODE_EXPIRY_SECONDS=600
      - CONFIG_TOKEN_EXPIRY_SECONDS=604800
      - NODE_ENV=development
      - FHIR_URL=http://openhim-core:5001/fhir
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - SEARCH_URL=http://search:9090/
      - METRICS_URL=http://metrics:1050
      - AUTH_URL=http://auth:4040
      - COUNTRY_CONFIG_URL=http://countryconfig:3040
      - NOTIFICATION_URL=http://notification:2020/
      - WORKFLOW_URL=http://workflow:5050/
      - APPLICATION_CONFIG_URL=http://config:2021/
      - CHECK_INVALID_TOKEN=true
  # User facing services
  workflow:
    image: opencrvs/ocrvs-workflow:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/workflow/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - RESOURCE_SERVICE_URL=http://countryconfig:3040/
      - HEARTH_URL=http://hearth:3447/fhir
      - OPENHIM_URL=http://openhim-core:5001
      - COUNTRY=${COUNTRY:-bgd} # PEN_TEST change to gbr
      - AUTH_URL=http://auth:4040
      - CHECK_INVALID_TOKEN=true
  search:
    image: opencrvs/ocrvs-search:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/search/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - ES_HOST=elasticsearch:9200
      - HEARTH_URL=http://hearth:3447/fhir
      - AUTH_URL=http://auth:4040
      - CHECK_INVALID_TOKEN=true
  metrics:
    image: opencrvs/ocrvs-metrics:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/metrics/Dockerfile
    restart: unless-stopped
    environment:
      - INFLUX_HOST=influxdb
      - INFLUX_PORT=8086
      - INFLUX_DB=ocrvs
      - AUTH_URL=http://auth:4040
      - COUNTRY_CONFIG_URL=http://countryconfig:3040/
      - CONFIG_API_URL=http://config:2021
      - FHIR_URL=http://openhim-core:5001/fhir
      - SEARCH_URL=http://search:9090/
      - CHECK_INVALID_TOKEN=true
  # END User facing services
  auth:
    image: opencrvs/ocrvs-auth:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/auth/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - CONFIG_TOKEN_EXPIRY_SECONDS=604800
      - CONFIG_SMS_CODE_EXPIRY_SECONDS=600
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
  user-mgnt:
    image: opencrvs/ocrvs-user-mgnt:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/user-mgnt/Dockerfile
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo1/user-mgnt
      - AUTH_URL=http://auth:4040
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
      - FHIR_URL=http://openhim-core:5001/fhir
      - HOST=0.0.0.0
      - CHECK_INVALID_TOKEN=true
  webhooks:
    image: opencrvs/ocrvs-webhooks:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/webhooks/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis://redis:6379
      - MONGO_URL=mongodb://mongo1/webhooks
      - AUTH_URL=http://auth:4040
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - FHIR_URL=http://openhim-core:5001/fhir
      - HOST=0.0.0.0
      - CHECK_INVALID_TOKEN=true
  notification:
    image: opencrvs/ocrvs-notification:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/notification/Dockerfile
    restart: unless-stopped
    environment:
      - AUTH_URL=http://auth:4040
      - COUNTRY=${COUNTRY:-bgd}
      - HOST=0.0.0.0
      - CHECK_INVALID_TOKEN=true
      - COUNTRY_CONFIG_URL=http://countryconfig:3040
  config:
    image: opencrvs/ocrvs-config:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/config/Dockerfile
    restart: unless-stopped
    environment:
      - AUTH_URL=http://auth:4040
      - HOST=0.0.0.0
      - PORT=2021
      - MONGO_URL=mongodb://mongo1/application-config
      - CHECK_INVALID_TOKEN=true
